### ISSUE TITLE
[JFYI] elg BUG: @root_validator: you MUST specify `skip_on_failure=True`

### ISSUE THREAD

**Issue by masc-it** [valeriobasile/uinauil#1]
Hi,

first thing first, thanks for your amazing job.

I wanted to notify a bug in the elg library that you're relying on. 
I've created a [MR](https://gitlab.com/european-language-grid/platform/python-client/-/merge_requests/102?commit_id=d7e89697053eae74328d9f0e62c9fe13460b9abc) that describes it (pretty simple fix), but I think they're not too active there. 

If you can do something to push it, it would be great for everybody :)

**Comment by valeriobasile** [comment]
Thanks @masc-it I had noticed the bug upstream, but this was a good reminder to act on it. As a workaround, I just downgraded the elg package. I should not impact anything since we are only using it to retrieve the data.
